highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://pvardanega.github.io/cv
author: Pierre-Jean Vardanéga

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /cv/
title: Pierre-Jean Vardanéga's Resume
name: Pierre-Jean Vardanéga
email: pierrejean.vardanega@gmail.com
email_full: mailto:pierrejean.vardanega@gmail.com
website: github.io/pvardanega
gravatar_url: https://www.gravatar.com/avatar/5b2b10e79ae4d4ae2b4bd3cc59f13cca
#website_full: https://biomadeira.github.io/sustain
github: pvardanega
twitter: pvardanega
#tel: +44 0000 000000
#tel_full: tel:+440000000000
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
#address: 44 Perth Street
#postcode: 1003
city: Lausanne
country: Switzerland
google_analytics: UA-79715049-1

# needed for travis-ci build
exclude: [vendor]
